# Generated by Django 4.0 on 2023-09-02 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_products_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='rating',
        ),
    ]
