# Generated by Django 4.0 on 2023-09-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
            options={
                'verbose_name_plural': 'Ratings',
                'ordering': ('value',),
            },
        ),
    ]
