# Generated by Django 4.0 on 2023-09-02 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_products_rating'),
        ('rating', '0002_alter_rating_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.products'),
        ),
    ]
